# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ACApps\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1498, 944)
        MainWindow.setStyleSheet("*{\n"
"    font-family:segoe ui;\n"
"    font-size:12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background: #e7eaec;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.fraInfo = QtWidgets.QFrame(self.centralwidget)
        self.fraInfo.setMinimumSize(QtCore.QSize(300, 150))
        self.fraInfo.setMaximumSize(QtCore.QSize(300, 150))
        self.fraInfo.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    background: #d0d6da;\n"
"}")
        self.fraInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraInfo.setObjectName("fraInfo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fraInfo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.fraInfo)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fraInfo)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fraInfo)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fraInfo)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.lblVerbindung = QtWidgets.QLabel(self.fraInfo)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblVerbindung.setFont(font)
        self.lblVerbindung.setObjectName("lblVerbindung")
        self.gridLayout_3.addWidget(self.lblVerbindung, 0, 1, 1, 1)
        self.lblACVersion = QtWidgets.QLabel(self.fraInfo)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblACVersion.setFont(font)
        self.lblACVersion.setObjectName("lblACVersion")
        self.gridLayout_3.addWidget(self.lblACVersion, 1, 1, 1, 1)
        self.lblACBuilt = QtWidgets.QLabel(self.fraInfo)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblACBuilt.setFont(font)
        self.lblACBuilt.setObjectName("lblACBuilt")
        self.gridLayout_3.addWidget(self.lblACBuilt, 2, 1, 1, 1)
        self.lblACLand = QtWidgets.QLabel(self.fraInfo)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblACLand.setFont(font)
        self.lblACLand.setObjectName("lblACLand")
        self.gridLayout_3.addWidget(self.lblACLand, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraInfo, 0, 0, 1, 1)
        self.fraMenu = QtWidgets.QFrame(self.centralwidget)
        self.fraMenu.setMinimumSize(QtCore.QSize(0, 150))
        self.fraMenu.setMaximumSize(QtCore.QSize(16777215, 150))
        self.fraMenu.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    background: #d0d6da;\n"
"}")
        self.fraMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMenu.setObjectName("fraMenu")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.fraMenu)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmdShowAttributuebertragung = QtWidgets.QPushButton(self.fraMenu)
        self.cmdShowAttributuebertragung.setMinimumSize(QtCore.QSize(200, 25))
        self.cmdShowAttributuebertragung.setMaximumSize(QtCore.QSize(200, 25))
        self.cmdShowAttributuebertragung.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdShowAttributuebertragung.setObjectName("cmdShowAttributuebertragung")
        self.gridLayout_5.addWidget(self.cmdShowAttributuebertragung, 1, 0, 1, 1)
        self.cmdShowRaumbuchExcel = QtWidgets.QPushButton(self.fraMenu)
        self.cmdShowRaumbuchExcel.setMinimumSize(QtCore.QSize(200, 25))
        self.cmdShowRaumbuchExcel.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdShowRaumbuchExcel.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdShowRaumbuchExcel.setObjectName("cmdShowRaumbuchExcel")
        self.gridLayout_5.addWidget(self.cmdShowRaumbuchExcel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.cmdShowRaumbuchPdf = QtWidgets.QPushButton(self.fraMenu)
        self.cmdShowRaumbuchPdf.setMinimumSize(QtCore.QSize(200, 25))
        self.cmdShowRaumbuchPdf.setMaximumSize(QtCore.QSize(200, 25))
        self.cmdShowRaumbuchPdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdShowRaumbuchPdf.setObjectName("cmdShowRaumbuchPdf")
        self.gridLayout_5.addWidget(self.cmdShowRaumbuchPdf, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraMenu, 0, 1, 1, 1)
        self.fraApp = QtWidgets.QFrame(self.centralwidget)
        self.fraApp.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    background: #d0d6da;\n"
"}")
        self.fraApp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraApp.setObjectName("fraApp")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.fraApp)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.fraApp)
        self.stackedWidget.setStyleSheet("QWidget{\n"
"    background: #d0d6da;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageEmpty = QtWidgets.QWidget()
        self.pageEmpty.setObjectName("pageEmpty")
        self.stackedWidget.addWidget(self.pageEmpty)
        self.pageRaumbuchgeneratorPdf = QtWidgets.QWidget()
        self.pageRaumbuchgeneratorPdf.setObjectName("pageRaumbuchgeneratorPdf")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.pageRaumbuchgeneratorPdf)
        self.gridLayout_15.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSpacing(10)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.treeUserAttrPdf = QtWidgets.QTreeWidget(self.pageRaumbuchgeneratorPdf)
        self.treeUserAttrPdf.setMinimumSize(QtCore.QSize(500, 350))
        self.treeUserAttrPdf.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.treeUserAttrPdf.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.treeUserAttrPdf.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeUserAttrPdf.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeUserAttrPdf.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeUserAttrPdf.setObjectName("treeUserAttrPdf")
        self.gridLayout_14.addWidget(self.treeUserAttrPdf, 6, 0, 1, 5)
        self.label_30 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_30.setMinimumSize(QtCore.QSize(100, 25))
        self.label_30.setMaximumSize(QtCore.QSize(1000, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_30.setObjectName("label_30")
        self.gridLayout_14.addWidget(self.label_30, 5, 6, 1, 6)
        self.tblAttrPdf = QtWidgets.QTableWidget(self.pageRaumbuchgeneratorPdf)
        self.tblAttrPdf.setMinimumSize(QtCore.QSize(800, 350))
        self.tblAttrPdf.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.tblAttrPdf.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tblAttrPdf.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblAttrPdf.setObjectName("tblAttrPdf")
        self.tblAttrPdf.setColumnCount(0)
        self.tblAttrPdf.setRowCount(0)
        self.tblAttrPdf.verticalHeader().setVisible(False)
        self.gridLayout_14.addWidget(self.tblAttrPdf, 6, 6, 1, 6)
        self.label_29 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_29.setMinimumSize(QtCore.QSize(100, 25))
        self.label_29.setMaximumSize(QtCore.QSize(100, 25))
        self.label_29.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_29.setObjectName("label_29")
        self.gridLayout_14.addWidget(self.label_29, 0, 6, 1, 1)
        self.txtPathTemplatePdf = QtWidgets.QLineEdit(self.pageRaumbuchgeneratorPdf)
        self.txtPathTemplatePdf.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathTemplatePdf.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathTemplatePdf.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathTemplatePdf.setObjectName("txtPathTemplatePdf")
        self.gridLayout_14.addWidget(self.txtPathTemplatePdf, 2, 1, 1, 11)
        self.label_17 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_17.setMinimumSize(QtCore.QSize(100, 25))
        self.label_17.setMaximumSize(QtCore.QSize(100, 25))
        self.label_17.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 5, 0, 1, 1)
        self.cmdAttrSavePdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdAttrSavePdf.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdAttrSavePdf.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdAttrSavePdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdAttrSavePdf.setObjectName("cmdAttrSavePdf")
        self.gridLayout_14.addWidget(self.cmdAttrSavePdf, 8, 10, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_20.setMinimumSize(QtCore.QSize(100, 25))
        self.label_20.setMaximumSize(QtCore.QSize(100, 25))
        self.label_20.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 1, 0, 1, 1)
        self.cmdExecRaumbuchPdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdExecRaumbuchPdf.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdExecRaumbuchPdf.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdExecRaumbuchPdf.setFont(font)
        self.cmdExecRaumbuchPdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdExecRaumbuchPdf.setObjectName("cmdExecRaumbuchPdf")
        self.gridLayout_14.addWidget(self.cmdExecRaumbuchPdf, 8, 11, 1, 1)
        self.cmdAddRowPdfUp = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdAddRowPdfUp.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdAddRowPdfUp.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdAddRowPdfUp.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdAddRowPdfUp.setObjectName("cmdAddRowPdfUp")
        self.gridLayout_14.addWidget(self.cmdAddRowPdfUp, 7, 9, 1, 1)
        self.cboSpaltenPdf = QtWidgets.QComboBox(self.pageRaumbuchgeneratorPdf)
        self.cboSpaltenPdf.setMinimumSize(QtCore.QSize(111, 25))
        self.cboSpaltenPdf.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboSpaltenPdf.setFont(font)
        self.cboSpaltenPdf.setStyleSheet("/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background:#b8c0c6;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.cboSpaltenPdf.setObjectName("cboSpaltenPdf")
        self.gridLayout_14.addWidget(self.cboSpaltenPdf, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem2, 0, 5, 1, 1)
        self.txtPathLogoPdf = QtWidgets.QLineEdit(self.pageRaumbuchgeneratorPdf)
        self.txtPathLogoPdf.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathLogoPdf.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathLogoPdf.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathLogoPdf.setObjectName("txtPathLogoPdf")
        self.gridLayout_14.addWidget(self.txtPathLogoPdf, 3, 1, 1, 11)
        self.cmdAttrImportPdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdAttrImportPdf.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdAttrImportPdf.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdAttrImportPdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdAttrImportPdf.setObjectName("cmdAttrImportPdf")
        self.gridLayout_14.addWidget(self.cmdAttrImportPdf, 8, 9, 1, 1)
        self.txtPathTargetPdf = QtWidgets.QLineEdit(self.pageRaumbuchgeneratorPdf)
        self.txtPathTargetPdf.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathTargetPdf.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathTargetPdf.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathTargetPdf.setObjectName("txtPathTargetPdf")
        self.gridLayout_14.addWidget(self.txtPathTargetPdf, 4, 1, 1, 11)
        self.cboAusrichtungPdf = QtWidgets.QComboBox(self.pageRaumbuchgeneratorPdf)
        self.cboAusrichtungPdf.setMinimumSize(QtCore.QSize(111, 25))
        self.cboAusrichtungPdf.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboAusrichtungPdf.setFont(font)
        self.cboAusrichtungPdf.setStyleSheet("/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background:#b8c0c6;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.cboAusrichtungPdf.setObjectName("cboAusrichtungPdf")
        self.gridLayout_14.addWidget(self.cboAusrichtungPdf, 0, 4, 1, 1)
        self.txtFilenamePdf = QtWidgets.QLineEdit(self.pageRaumbuchgeneratorPdf)
        self.txtFilenamePdf.setMinimumSize(QtCore.QSize(0, 25))
        self.txtFilenamePdf.setMaximumSize(QtCore.QSize(300, 25))
        self.txtFilenamePdf.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtFilenamePdf.setObjectName("txtFilenamePdf")
        self.gridLayout_14.addWidget(self.txtFilenamePdf, 5, 1, 1, 5)
        self.cboFormatPdf = QtWidgets.QComboBox(self.pageRaumbuchgeneratorPdf)
        self.cboFormatPdf.setMinimumSize(QtCore.QSize(111, 25))
        self.cboFormatPdf.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboFormatPdf.setFont(font)
        self.cboFormatPdf.setStyleSheet("/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background:#b8c0c6;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.cboFormatPdf.setObjectName("cboFormatPdf")
        self.gridLayout_14.addWidget(self.cboFormatPdf, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem3, 0, 8, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 0, 2, 1, 1)
        self.cmdTargetLogo = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdTargetLogo.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdTargetLogo.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdTargetLogo.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdTargetLogo.setObjectName("cmdTargetLogo")
        self.gridLayout_14.addWidget(self.cmdTargetLogo, 3, 12, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_27.setMinimumSize(QtCore.QSize(100, 25))
        self.label_27.setMaximumSize(QtCore.QSize(100, 25))
        self.label_27.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.gridLayout_14.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_16.setMinimumSize(QtCore.QSize(100, 25))
        self.label_16.setMaximumSize(QtCore.QSize(100, 25))
        self.label_16.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 0, 0, 1, 1)
        self.cmdTargetTemplatePdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdTargetTemplatePdf.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdTargetTemplatePdf.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdTargetTemplatePdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdTargetTemplatePdf.setObjectName("cmdTargetTemplatePdf")
        self.gridLayout_14.addWidget(self.cmdTargetTemplatePdf, 2, 12, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_26.setMinimumSize(QtCore.QSize(100, 25))
        self.label_26.setMaximumSize(QtCore.QSize(100, 25))
        self.label_26.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.gridLayout_14.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_28.setMinimumSize(QtCore.QSize(100, 25))
        self.label_28.setMaximumSize(QtCore.QSize(100, 25))
        self.label_28.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_28.setObjectName("label_28")
        self.gridLayout_14.addWidget(self.label_28, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.pageRaumbuchgeneratorPdf)
        self.label_25.setMinimumSize(QtCore.QSize(100, 25))
        self.label_25.setMaximumSize(QtCore.QSize(100, 25))
        self.label_25.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 4, 0, 1, 1)
        self.cmdAddRowPdfDown = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdAddRowPdfDown.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdAddRowPdfDown.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdAddRowPdfDown.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdAddRowPdfDown.setObjectName("cmdAddRowPdfDown")
        self.gridLayout_14.addWidget(self.cmdAddRowPdfDown, 7, 10, 1, 1)
        self.cmdTargetPdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdTargetPdf.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdTargetPdf.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdTargetPdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdTargetPdf.setObjectName("cmdTargetPdf")
        self.gridLayout_14.addWidget(self.cmdTargetPdf, 4, 12, 1, 1)
        self.cmdDeleteRowPdf = QtWidgets.QPushButton(self.pageRaumbuchgeneratorPdf)
        self.cmdDeleteRowPdf.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdDeleteRowPdf.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdDeleteRowPdf.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdDeleteRowPdf.setObjectName("cmdDeleteRowPdf")
        self.gridLayout_14.addWidget(self.cmdDeleteRowPdf, 7, 11, 1, 1)
        self.txtProjektnamePdf = QtWidgets.QLineEdit(self.pageRaumbuchgeneratorPdf)
        self.txtProjektnamePdf.setMinimumSize(QtCore.QSize(0, 25))
        self.txtProjektnamePdf.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtProjektnamePdf.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtProjektnamePdf.setObjectName("txtProjektnamePdf")
        self.gridLayout_14.addWidget(self.txtProjektnamePdf, 1, 1, 1, 4)
        self.cboLayerPdf = QtWidgets.QComboBox(self.pageRaumbuchgeneratorPdf)
        self.cboLayerPdf.setMinimumSize(QtCore.QSize(111, 25))
        self.cboLayerPdf.setMaximumSize(QtCore.QSize(220, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.cboLayerPdf.setFont(font)
        self.cboLayerPdf.setStyleSheet("/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background:#b8c0c6;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.cboLayerPdf.setObjectName("cboLayerPdf")
        self.gridLayout_14.addWidget(self.cboLayerPdf, 7, 6, 1, 2)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageRaumbuchgeneratorPdf)
        self.pageRaumbuchgenerator = QtWidgets.QWidget()
        self.pageRaumbuchgenerator.setObjectName("pageRaumbuchgenerator")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pageRaumbuchgenerator)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.txtPathExcel = QtWidgets.QLineEdit(self.pageRaumbuchgenerator)
        self.txtPathExcel.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathExcel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathExcel.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathExcel.setObjectName("txtPathExcel")
        self.gridLayout_9.addWidget(self.txtPathExcel, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 9, 1, 1, 1)
        self.txtPathCSV = QtWidgets.QLineEdit(self.pageRaumbuchgenerator)
        self.txtPathCSV.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathCSV.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathCSV.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathCSV.setObjectName("txtPathCSV")
        self.gridLayout_9.addWidget(self.txtPathCSV, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem6, 5, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setHorizontalSpacing(15)
        self.gridLayout_11.setVerticalSpacing(10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 1, 0, 1, 1)
        self.cmdImportAttr = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdImportAttr.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdImportAttr.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdImportAttr.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdImportAttr.setObjectName("cmdImportAttr")
        self.gridLayout_11.addWidget(self.cmdImportAttr, 1, 3, 1, 1)
        self.cmdAttrAdd = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdAttrAdd.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdAttrAdd.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdAttrAdd.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdAttrAdd.setObjectName("cmdAttrAdd")
        self.gridLayout_11.addWidget(self.cmdAttrAdd, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 1, 2, 1, 1)
        self.treeUserAttr = QtWidgets.QTreeWidget(self.pageRaumbuchgenerator)
        self.treeUserAttr.setMinimumSize(QtCore.QSize(480, 350))
        self.treeUserAttr.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.treeUserAttr.setObjectName("treeUserAttr")
        self.gridLayout_11.addWidget(self.treeUserAttr, 0, 0, 1, 2)
        self.cmdDeleteRow = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdDeleteRow.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdDeleteRow.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdDeleteRow.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdDeleteRow.setObjectName("cmdDeleteRow")
        self.gridLayout_11.addWidget(self.cmdDeleteRow, 1, 4, 1, 1)
        self.tblAttr = QtWidgets.QTableWidget(self.pageRaumbuchgenerator)
        self.tblAttr.setMinimumSize(QtCore.QSize(480, 350))
        self.tblAttr.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.tblAttr.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAttr.setObjectName("tblAttr")
        self.tblAttr.setColumnCount(3)
        self.tblAttr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttr.setHorizontalHeaderItem(2, item)
        self.tblAttr.verticalHeader().setVisible(False)
        self.gridLayout_11.addWidget(self.tblAttr, 0, 3, 1, 3)
        self.cmdExecRaumbuch = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdExecRaumbuch.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdExecRaumbuch.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.cmdExecRaumbuch.setFont(font)
        self.cmdExecRaumbuch.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdExecRaumbuch.setObjectName("cmdExecRaumbuch")
        self.gridLayout_11.addWidget(self.cmdExecRaumbuch, 1, 6, 1, 1)
        self.cmdSaveCSV = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdSaveCSV.setMinimumSize(QtCore.QSize(150, 25))
        self.cmdSaveCSV.setMaximumSize(QtCore.QSize(150, 25))
        self.cmdSaveCSV.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdSaveCSV.setObjectName("cmdSaveCSV")
        self.gridLayout_11.addWidget(self.cmdSaveCSV, 1, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 1, 7, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 0, 6, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_11, 6, 1, 3, 1)
        self.label_12 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 4, 0, 1, 1)
        self.txtPathTarget = QtWidgets.QLineEdit(self.pageRaumbuchgenerator)
        self.txtPathTarget.setMinimumSize(QtCore.QSize(0, 25))
        self.txtPathTarget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtPathTarget.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtPathTarget.setObjectName("txtPathTarget")
        self.gridLayout_9.addWidget(self.txtPathTarget, 3, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem11, 8, 0, 1, 1)
        self.txtCell = QtWidgets.QLineEdit(self.pageRaumbuchgenerator)
        self.txtCell.setMinimumSize(QtCore.QSize(150, 25))
        self.txtCell.setMaximumSize(QtCore.QSize(150, 25))
        self.txtCell.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtCell.setObjectName("txtCell")
        self.gridLayout_9.addWidget(self.txtCell, 7, 0, 1, 1)
        self.cmdTarget = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdTarget.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdTarget.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdTarget.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdTarget.setObjectName("cmdTarget")
        self.gridLayout_9.addWidget(self.cmdTarget, 3, 2, 1, 1)
        self.txtFilename = QtWidgets.QLineEdit(self.pageRaumbuchgenerator)
        self.txtFilename.setMinimumSize(QtCore.QSize(0, 25))
        self.txtFilename.setMaximumSize(QtCore.QSize(300, 25))
        self.txtFilename.setStyleSheet("QLineEdit{\n"
"    font-size:12px;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    background: #ffffff;\n"
"}")
        self.txtFilename.setObjectName("txtFilename")
        self.gridLayout_9.addWidget(self.txtFilename, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_10.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_6.setMinimumSize(QtCore.QSize(150, 25))
        self.label_6.setMaximumSize(QtCore.QSize(150, 25))
        self.label_6.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_5.setMinimumSize(QtCore.QSize(150, 25))
        self.label_5.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.cmdCSV = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdCSV.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdCSV.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdCSV.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdCSV.setObjectName("cmdCSV")
        self.gridLayout_9.addWidget(self.cmdCSV, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.pageRaumbuchgenerator)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_13.setStyleSheet("QLabel{\n"
"    font-family:segoe ui;    \n"
"    font-size:12px;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 6, 0, 1, 1)
        self.cmdExcel = QtWidgets.QPushButton(self.pageRaumbuchgenerator)
        self.cmdExcel.setMinimumSize(QtCore.QSize(30, 25))
        self.cmdExcel.setMaximumSize(QtCore.QSize(30, 25))
        self.cmdExcel.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#d0d6da;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.cmdExcel.setObjectName("cmdExcel")
        self.gridLayout_9.addWidget(self.cmdExcel, 1, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageRaumbuchgenerator)
        self.pageAttributuebertragung = QtWidgets.QWidget()
        self.pageAttributuebertragung.setObjectName("pageAttributuebertragung")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.pageAttributuebertragung)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gew_user_selected = QtWidgets.QPushButton(self.pageAttributuebertragung)
        self.gew_user_selected.setMinimumSize(QtCore.QSize(150, 25))
        self.gew_user_selected.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.gew_user_selected.setFont(font)
        self.gew_user_selected.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.gew_user_selected.setObjectName("gew_user_selected")
        self.gridLayout_12.addWidget(self.gew_user_selected, 2, 1, 1, 1)
        self.category = QtWidgets.QComboBox(self.pageAttributuebertragung)
        self.category.setMinimumSize(QtCore.QSize(111, 25))
        self.category.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.category.setFont(font)
        self.category.setStyleSheet("/*STYLESHEET FÜR QComboBox*/\n"
"\n"
"QComboBox {\n"
"    font-size:12px;\n"
"    border: solid;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background:#b8c0c6;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: #e7eaec;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on {\n"
"    background:#a1abb1;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'//firma.local/dfs/Laufwerk-Z/Daten - Intern/Kosten/09 SQL Preisdatenbank/07_Python Oberfläche/qss/down-arrow.png\');\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #d0d6da;\n"
"    border-radius: 0px;\n"
"    background: #ffffff;\n"
"    selection-color: #000000;\n"
"    selection-background-color: #d0d6da;\n"
"}")
        self.category.setObjectName("category")
        self.category.addItem("")
        self.category.addItem("")
        self.gridLayout_12.addWidget(self.category, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 0, 3, 1, 1)
        self.gew_intern_selected = QtWidgets.QPushButton(self.pageAttributuebertragung)
        self.gew_intern_selected.setMinimumSize(QtCore.QSize(150, 25))
        self.gew_intern_selected.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.gew_intern_selected.setFont(font)
        self.gew_intern_selected.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.gew_intern_selected.setObjectName("gew_intern_selected")
        self.gridLayout_12.addWidget(self.gew_intern_selected, 2, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 4, 1, 1, 1)
        self.gew_intern_attr = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gew_intern_attr.setFont(font)
        self.gew_intern_attr.setText("")
        self.gew_intern_attr.setObjectName("gew_intern_attr")
        self.gridLayout_12.addWidget(self.gew_intern_attr, 5, 3, 1, 1)
        self.gew_user_attr = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.gew_user_attr.setMinimumSize(QtCore.QSize(0, 20))
        self.gew_user_attr.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gew_user_attr.setFont(font)
        self.gew_user_attr.setText("")
        self.gew_user_attr.setObjectName("gew_user_attr")
        self.gridLayout_12.addWidget(self.gew_user_attr, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.label_23.setMinimumSize(QtCore.QSize(0, 20))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 0, 0, 1, 1)
        self.intern_attr = QtWidgets.QTreeWidget(self.pageAttributuebertragung)
        self.intern_attr.setMinimumSize(QtCore.QSize(500, 0))
        self.intern_attr.setMaximumSize(QtCore.QSize(500, 16777215))
        self.intern_attr.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.intern_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.intern_attr.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.intern_attr.setAutoExpandDelay(1)
        self.intern_attr.setAnimated(True)
        self.intern_attr.setAllColumnsShowFocus(True)
        self.intern_attr.setWordWrap(True)
        self.intern_attr.setColumnCount(2)
        self.intern_attr.setObjectName("intern_attr")
        self.intern_attr.headerItem().setText(0, "1")
        self.intern_attr.headerItem().setText(1, "2")
        self.intern_attr.header().setCascadingSectionResizes(True)
        self.intern_attr.header().setDefaultSectionSize(150)
        self.gridLayout_12.addWidget(self.intern_attr, 3, 3, 1, 2)
        self.gew_user_attr_2 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.gew_user_attr_2.setMinimumSize(QtCore.QSize(0, 20))
        self.gew_user_attr_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gew_user_attr_2.setFont(font)
        self.gew_user_attr_2.setText("")
        self.gew_user_attr_2.setObjectName("gew_user_attr_2")
        self.gridLayout_12.addWidget(self.gew_user_attr_2, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 4, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 4, 0, 1, 1)
        self.arrow = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.arrow.setFont(font)
        self.arrow.setAlignment(QtCore.Qt.AlignCenter)
        self.arrow.setObjectName("arrow")
        self.gridLayout_12.addWidget(self.arrow, 8, 2, 1, 1)
        self.user_attr = QtWidgets.QTreeWidget(self.pageAttributuebertragung)
        self.user_attr.setMinimumSize(QtCore.QSize(500, 0))
        self.user_attr.setMaximumSize(QtCore.QSize(500, 16777215))
        self.user_attr.setStyleSheet("*{\n"
"    background: #ffffff;\n"
"    border-radius: 0px;\n"
"}")
        self.user_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_attr.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.user_attr.setAutoExpandDelay(1)
        self.user_attr.setAnimated(True)
        self.user_attr.setAllColumnsShowFocus(True)
        self.user_attr.setWordWrap(True)
        self.user_attr.setColumnCount(1)
        self.user_attr.setObjectName("user_attr")
        self.user_attr.headerItem().setText(0, "1")
        self.user_attr.header().setCascadingSectionResizes(True)
        self.user_attr.header().setDefaultSectionSize(300)
        self.gridLayout_12.addWidget(self.user_attr, 3, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 4, 4, 1, 1)
        self.count = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.count.setFont(font)
        self.count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count.setObjectName("count")
        self.gridLayout_12.addWidget(self.count, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 2, 3, 1, 1)
        self.execute = QtWidgets.QPushButton(self.pageAttributuebertragung)
        self.execute.setMinimumSize(QtCore.QSize(0, 25))
        self.execute.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.execute.setFont(font)
        self.execute.setAutoFillBackground(False)
        self.execute.setStyleSheet("QPushButton{\n"
"    font-size:12px;\n"
"    background:#b8c0c6;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-size:12px;\n"
"    background:#e7eaec;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    font-size:12px;\n"
"    background:#a1abb1;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    padding-top: 1px;\n"
"    padding-left: 2px;\n"
"}")
        self.execute.setObjectName("execute")
        self.gridLayout_12.addWidget(self.execute, 10, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem12, 0, 2, 1, 1)
        self.gew_intern_attr_2 = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.gew_intern_attr_2.setFont(font)
        self.gew_intern_attr_2.setText("")
        self.gew_intern_attr_2.setObjectName("gew_intern_attr_2")
        self.gridLayout_12.addWidget(self.gew_intern_attr_2, 5, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 0, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.pageAttributuebertragung)
        self.line_3.setMinimumSize(QtCore.QSize(0, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("*{\n"
"background-color: black;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_12.addWidget(self.line_3, 1, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.pageAttributuebertragung)
        self.line_2.setMinimumSize(QtCore.QSize(0, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("*{\n"
"background-color: black;\n"
"}")
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_12.addWidget(self.line_2, 6, 0, 1, 5)
        self.final_user_attr = QtWidgets.QLabel(self.pageAttributuebertragung)
        self.final_user_attr.setMinimumSize(QtCore.QSize(0, 20))
        self.final_user_attr.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.final_user_attr.setFont(font)
        self.final_user_attr.setText("")
        self.final_user_attr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.final_user_attr.setObjectName("final_user_attr")
        self.gridLayout_12.addWidget(self.final_user_attr, 8, 0, 1, 2)
        self.final_intern_attr = QtWidgets.QLabel(self.pageAttributuebertragung)
        font = QtGui.QFont()
        font.setFamily("segoe ui")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.final_intern_attr.setFont(font)
        self.final_intern_attr.setText("")
        self.final_intern_attr.setObjectName("final_intern_attr")
        self.gridLayout_12.addWidget(self.final_intern_attr, 8, 3, 1, 2)
        self.line = QtWidgets.QFrame(self.pageAttributuebertragung)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("*{\n"
"background-color: black;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_12.addWidget(self.line, 9, 0, 1, 5)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageAttributuebertragung)
        self.gridLayout_7.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fraApp, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1498, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Verbindung:"))
        self.label_3.setText(_translate("MainWindow", "Land:"))
        self.label_2.setText(_translate("MainWindow", "ArchiCad Built:"))
        self.label_4.setText(_translate("MainWindow", "ArchiCad Version:"))
        self.lblVerbindung.setText(_translate("MainWindow", "Text"))
        self.lblACVersion.setText(_translate("MainWindow", "Text"))
        self.lblACBuilt.setText(_translate("MainWindow", "Text"))
        self.lblACLand.setText(_translate("MainWindow", "Text"))
        self.cmdShowAttributuebertragung.setText(_translate("MainWindow", "Attributübertragung"))
        self.cmdShowRaumbuchExcel.setText(_translate("MainWindow", "Raumbuch Generator Excel"))
        self.cmdShowRaumbuchPdf.setText(_translate("MainWindow", "Raumbuch Generator PDF"))
        self.treeUserAttrPdf.headerItem().setText(0, _translate("MainWindow", "1"))
        self.label_30.setText(_translate("MainWindow", "Typ: ü (Überschrift), d (Datensatz), l (Leerbereich), s (Seitenumbruch) / Inhalt: Beschriftung/Attribut/Gruppe-Interner Name/Herkunft"))
        self.label_29.setText(_translate("MainWindow", "Spalten:"))
        self.label_17.setText(_translate("MainWindow", "Dateiname [.pdf]:"))
        self.cmdAttrSavePdf.setText(_translate("MainWindow", "Als Vorlage speichern"))
        self.label_20.setText(_translate("MainWindow", "Projektname:"))
        self.cmdExecRaumbuchPdf.setText(_translate("MainWindow", "Ausführen"))
        self.cmdAddRowPdfUp.setText(_translate("MainWindow", "Zeile darüber"))
        self.cmdAttrImportPdf.setText(_translate("MainWindow", "Attribute importieren"))
        self.cmdTargetLogo.setText(_translate("MainWindow", "..."))
        self.label_27.setText(_translate("MainWindow", "Pfad Template:"))
        self.label_16.setText(_translate("MainWindow", "Format:"))
        self.cmdTargetTemplatePdf.setText(_translate("MainWindow", "..."))
        self.label_26.setText(_translate("MainWindow", "Pfad Logo:"))
        self.label_28.setText(_translate("MainWindow", "Ausrichtung:"))
        self.label_25.setText(_translate("MainWindow", "Pfad Zielordner:"))
        self.cmdAddRowPdfDown.setText(_translate("MainWindow", "Zeile darunter"))
        self.cmdTargetPdf.setText(_translate("MainWindow", "..."))
        self.cmdDeleteRowPdf.setText(_translate("MainWindow", "Zeile löschen"))
        self.cmdImportAttr.setText(_translate("MainWindow", "Attribute importieren"))
        self.cmdAttrAdd.setText(_translate("MainWindow", "Hinzufügen"))
        self.treeUserAttr.headerItem().setText(0, _translate("MainWindow", "1"))
        self.treeUserAttr.headerItem().setText(1, _translate("MainWindow", "2"))
        self.cmdDeleteRow.setText(_translate("MainWindow", "Zeile löschen"))
        item = self.tblAttr.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Attribut"))
        item = self.tblAttr.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Herkunft"))
        item = self.tblAttr.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zelle"))
        self.cmdExecRaumbuch.setText(_translate("MainWindow", "Ausführen"))
        self.cmdSaveCSV.setText(_translate("MainWindow", "Als Vorlage speichern"))
        self.label_12.setText(_translate("MainWindow", "Dateiname [.xlsm]:"))
        self.cmdTarget.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Pfad Attributszuordnung:"))
        self.label_6.setText(_translate("MainWindow", "Pfad Excel-Template:"))
        self.label_11.setText(_translate("MainWindow", "Pfad Zielordner:"))
        self.label_5.setText(_translate("MainWindow", "Vorlagendateien wählen:"))
        self.cmdCSV.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "Zelle:"))
        self.cmdExcel.setText(_translate("MainWindow", "..."))
        self.gew_user_selected.setText(_translate("MainWindow", "Attribut auswählen"))
        self.category.setItemText(0, _translate("MainWindow", "Räume"))
        self.category.setItemText(1, _translate("MainWindow", "Wände"))
        self.label_22.setText(_translate("MainWindow", "Vorhandene Elemente:"))
        self.gew_intern_selected.setText(_translate("MainWindow", "Attribut auswählen"))
        self.label_14.setText(_translate("MainWindow", "Gruppe:"))
        self.label_23.setText(_translate("MainWindow", "Folgende Übertragung der Attrbiute wird durchgeführt:"))
        self.label_21.setText(_translate("MainWindow", "Elementtyp:"))
        self.intern_attr.setSortingEnabled(True)
        self.label_19.setText(_translate("MainWindow", "Gewähltes internes Attribut:"))
        self.label_18.setText(_translate("MainWindow", "Gewähltes benutzerdef. Attribut:"))
        self.arrow.setText(_translate("MainWindow", ">>>"))
        self.user_attr.setSortingEnabled(True)
        self.label_9.setText(_translate("MainWindow", "Benutzerdefinierte Attribute:"))
        self.label_15.setText(_translate("MainWindow", "Gewähltes internes Attribut:"))
        self.count.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Interne Attribute:"))
        self.execute.setText(_translate("MainWindow", "Ausführen"))
